// v6.3.1800
(function(h,l,M,E,N,u,t,x,fa,ga,ha,y,U,F,ia,z,ja,ka){function m(a,b,c,d){return function(){a.call(b,c,d)}}function B(a){return"object"==typeof a}function xa(){for(var a=32,b="";a--;)b+=(0|16*N.random()).toString(16);return b}function A(a,b,c,d){var e;(e=a.addEventListener)?e.call(a,b,c,0):a.attachEvent(d||"on"+b,c)}function la(){return M&&"preview"==M.loadPurpose}function C(a,b){for(var c in a)a.hasOwnProperty(c)&&a[c]!==n&&b(a[c],c)}function O(a,b){var c=[];C(a,function(a,e){c.push(fa(e)+"="+fa(b?
(typeof a).charAt(0)+(B(a)&&a?O(a,b):a):a))});return c.join("&")}function G(a,b){if(!a)throw Error(b);}function ya(a){var b={};C(a,function(a,d){b[d]=a});return b}function za(a){P[ma]=a;return ma++}function na(){var a=h.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){H=a;V=c;W=d})}function Q(a,b){function c(a){return"expires="+(new u(a)).toGMTString()+";"}var d="path=/;",e=a.g(6);e&&(d+="domain="+e+";");return{m:function(e,q){a.g(1,1)&&(l.cookie=e+"="+q+";"+c(+new u+(b?6E10:6E4))+d)},A:function(b){if(a.g(1,
1))return(l.cookie.match("(^|;)\\s*"+b+"=([^;]*)")||[])[2]||n},ba:function(a){l.cookie=a+"=;"+c(0)+d}}}function I(a){function b(){var a=d[z];a&&(d[z]=a[y](":_GS_:")[0])}var c;if(I[a])return I[a];var d=h.top;I[a]=c=function(){b();d[z]=(d[z]||"")+":_GS_:"+[a,c.f,c.I]};try{var e=d[z]||"";if(-1!=e[ka](":_GS_:")){var f=e[y](":_GS_:")[1][y](",");f[0]==a&&(c.f=f[1]||"",c.I=f[2]||"")}b()}catch(q){d={}}return c}function oa(a){var b=l[ja]("head")[0],c=l[ha]("script");c.src=a;b.appendChild(c);return function(){c&&
b.removeChild(c);c=null}}function R(a){var b=v.c;b||(b=v.c=function(a){b.q.push(a)},b.q=[]);b(a)}function J(a){function b(b){f.m(d,q.f=b?"":[X,548*k.D+2019,379*k.B+4621,+new u].join(":"));a.s(11,b?0:X)}function c(){h&&"-"!==h?(f.m(e,h+(m?"|"+m:"")),R(["i",a.b,h,m])):(f.m(e,""),R(["u",a.b]))}var d="gs_u_"+a.b,e="gs_v_"+a.b,f=Q(a,1),q=I(a.b),g=(f.A(d)||q.f||"")[y](/(?::|%3A)/),p=1,X=a.g(11,g[0])||(p=0,xa()),Aa=((g[1]||2019)-2019)/548,l=((g[2]||4621)-4621)/379,g=(g[3]||0)/1E3,h=a.g(13),m=a.g(14),k;k=
{f:X,C:h,D:Aa,B:l,ga:~~g,na:p,ea:function(a,c){k.B+=+a;k.D+=+c;b()},qa:function(a){h=k.C=a;c()},oa:b,ka:function(){var b=f.A("gs_p_"+a.b)||q.I;f.ba("gs_p_"+a.b);return a.i!==n?a.i:b},M:m,pa:function(a){G(/^[0-9a-f]{64}$/.test(a),"Invalid auth signature");m=k.M=a;c()}};h&&c();return k}function S(a,b,c,d,e){var f=m,q=t(function(){f();Y=(Y+1)%Z[F];c.et&&(c.et=0);c.rt=1;--e&&S(a,b,c,d,e)},1E4),g=J(a);c.cb=za(function(a,b){d(a,b);f();x(q)});c.a=a.b;c.au=g.M;c.id=g.f;c.cid=g.C;c.tv=ga;g=b+"?"+O(c);f=oa((Ba?
"https":"http")+"://"+Z[Y]+".gosquared.com/"+g)}function pa(a,b,c){var d=l[ha]("a");d.href=b||h.location.href;b=d.href;a.g(7,1)||(b=b[U](/\?[^#]*/,""));a.g(8)||(b=b[U](/#.*$/,""));return{ra:b,t:c!==n?c:l.title,T:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),S:/fb_xd_(bust|fragment)/.test(b)}}function qa(a){var b;if(a.L){var c=pa(a);!a.g(9)&&c.T||c.S||la()||(b=O(a.h,1))&&S(a,"prop",{cp:b},m,5)}else t(function(){qa(a)},100)}function ra(a,b,c){var d=a.h=a.h||{};G(b||B(c),"Not an object");b?d[b]=
c:d=a.h=c;!a.V&&a.L&&(a.V=t(function(){qa(a);a.V=0},100))}function Ca(){var a=0,b=0,c;E&&(a=E.width,b=E.height);c=(c=h.orientation)&&(c+360)%180;return{K:c?b:a,J:c?a:b,$:E&&E.colorDepth||"-",fa:M.language||M.browserLanguage||"-",aa:l.characterSet||l.charSet||"-",ca:h.devicePixelRatio||1,ha:(new u).getTimezoneOffset()}}function aa(){function a(a){return h["inner"+a]||c&&c[e="client"+a]||d&&d[e]}function b(a){return N.max(d[e="scroll"+a]|0,c[e]|0,d[e="offset"+a]|0,c[e]|0,d[e="client"+a]|0,c[e]|0)}var c=
l.documentElement,d=l.body||c,e;return{X:a("Width"),W:a("Height"),P:b("Width"),O:b("Height"),o:h.pageXOffset||c&&c.scrollLeft||0,u:h.pageYOffset||c&&c.scrollTop||0}}function sa(a){a.j&&(a.j=0,a.w=new u-a.F+(a.w||0))}function ba(a){x(a.ia);a.ia=t(m(sa,0,a),15E3);a.j||(a.j=1,a.F=new u)}function Da(a){var b=a.w,c=new u;a.j&&(b+=c-a.F,a.F=c);a.w=0;return b}function Ea(a){ba(a);var b=aa();b.u>a.H&&(a.H=b.u);b.o>a.G&&(a.G=b.o)}function Fa(a){var b=m(ba,0,a);A(l,"mousemove",b);A(l,"keydown",b);A(h,"scroll",
m(Ea,0,a));A(l,"focus",b,"focusin");A(l,"blur",m(sa,0,a),"focusout")}function Ga(a){a=a.g(10,l.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[U](/^.*?\/\//,"")[ka](location.host);return{R:+(0<=b&&8>=b),ma:a}}function T(a,b,c,d){if(a.i!==n){if(!c){var e=aa();c={vw:e.X,vh:e.W,dw:e.P,dh:e.O,st:e.u,sl:e.o,mst:a.H,msl:a.G}}c.i=a.i;c.e=b;c.et=Da(a);r&&(c.bc=1);a.U&&H&&(a.U=0,c.o_si=H,c.o_vi=V,c.o_ci=W);S(a,"ping",c,function(){d&&d();x(a.l);a.l=t(m(T,0,a),[7E3,12E3][a.ja++]||
17500+5E3*N.random())},5)}else t(function(){T(a,b,c,d)},5E3)}function Ha(a){if(a.i!==n){var b=Q(a);a.g(1,1)?b.m("gs_p_"+a.b,a.i):(b=I(a.b),b.I=a.i,b())}}function ca(a,b,c){G(a,"Event name is required");b&&b.call&&(c=b,b=n);if(b===""+b||b===+b)b={caption:b};b=ya(b||{});b.gs_evt_name=a;T(this,"event",b,c)}function da(a,b,c){a&&a.call&&(c=a,a=n);b&&b.call&&(c=b,b=n);var d=this,e=pa(d,a,b),f=Ga(d),q=d.i===n&&!f.R;b=d.L=J(d);var g=Ca(),p=aa(),k=d.g(5);b.ea(1,q);x(d.l);d.w=0;d.j=0;ba(d);!d.g(9)&&e.T||e.S||
la()||g.K&&g.J&&10>g.K&&10>g.J||(d.H=p.u,d.G=p.o,e={cs:g.aa,cd:g.$,la:g.fa,sw:g.K,sh:g.J,dp:g.ca,pu:e.ra,pt:e.t||"-",ri:f.R,ru:f.ma,re:b.na,vi:b.D,pv:b.B,lv:b.ga,vw:p.X,vh:p.W,dw:p.P,dh:p.O,st:p.u,sl:p.o,un:d.g(3),pp:b.ka(),ec:k,aip:d.g(2)?1:n,tz:g.ha},d.h&&(e.cp=O(d.h,1)),d.Z||!1===d.g(15)||(e.rc=1,d.Z=1),r&&(d.uid=b.f,e.bc=1),H?(e.o_si=H,e.o_vi=V,e.o_ci=W):d.U=1,d.ja=0,S(d,"pv",e,function(a,b){a!==n&&(d.i=a,x(d.l),d.l=t(m(T,0,d),5E3),c&&c());if(b){R(b);var e=v.c;e.c||(e.c=[2,d.b,d.g(15),d.g(11),
d.g(6)]);var e=(d.g(15)||{}).js||"https://js.gs-chat.com/chat.js",f=b[0];ta||(ta=1,oa(e+(f?"?"+f.v:"")))}},5),d.i!==n?a!==n&&(d.i=n):(t(m(Fa,0,d),500),A(h,"beforeunload",m(Ha,0,d))))}function ua(a){var b="gs_v_"+a,c=this,d=[];d[12]=c.b=a;c.s=function(a,b,e){4==a&&(ra(c,e,b),b=c.h);13==a&&(ra(c,"id",b),b=b||"-",J(c).qa(b));14==a&&J(c).pa(b);d[a]=b};c.g=function(a,e){function g(){var a=Q(c,1).A(b),d;/\|[0-9a-f]{32,64}/.test(a)&&(a=a[y]("|"),d=a.pop(),a=a.join("|"));return{Y:d,C:a}}return a in d?d[a]:
13==a?g().C||e:14==a?g().Y||e:e};var e;c.da=function(){e=t(m(da,c),20)};c.N=function(){x(c.l);x(e)}}function ea(a,b,c){if(!a)for(a in k)return k[a];if(k[b||a])return k[b||a];a=k[b||a]=new ua(a);c&&a.da();return a}function D(a,b,c,d,e){b?a.call(k[b],c,d,e):C(k,function(b){a.call(b,c,d,e)})}function Ia(a,b,c,d){function e(a,b){b=b||(B(a)?a:{});B(a)||(b[z]=a);G(b[z],"No Name");g.push(b);return h}function f(a){for(var b=0;b<a[F];)e(a[b++]);return h}function k(){D(function(){var a=Q(this,1),d="gs_t_"+
this.b,e=a.A(d)||0;a.m(d,+new u);ca.call(this,"_transaction",{d:JSON.stringify({id:b,pt:{ts:+e},i:g,d:c})})},a)}!c&&B(b)&&(c=b,b=c.id);var g=[],h;d&&f(d);c&&c.track&&k();return h={id:b,addItem:e,addItems:f,track:k}}function Ja(a,b){!b&&B(a)&&(b=a,a=b.id,!a&&b.email&&(a="email:"+b.email));G(a,"ID or email required");this.s(13,a);b&&this.s(4,b)}function v(a,b,c,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(c=b,b=0),ea(a,b,c||c===n);else if(P[a])P[a](b,c),delete P[a];else{var e=function(a,
b,c){f?k[f].s(a,b,c):C(k,function(d){d.s(a,b,c)})};a=a[y](".");var f;1<a[F]&&(f=a.shift());a=a[0];var h={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4,chat:15};if(/transaction$/i.test(a))return Ia(f,b,c,d);if("get"==a)return c=h[(b+"")[ia]()]||b,f?d=k[f].g(c):C(k,function(a){d=a.g(c)}),d;"set"==a?(a=(b+"")[y]("."),b=a.shift(),e(h[b[ia]()]||b,c,a.join("."))):
"track"==a?D(da,f,b,c,d):"event"==a?D(ca,f,b,c,d):"cancel"==a?D(function(){this.N()},f):"noCookies"==a?e(1,0):"anonymizeIP"==a?e(2,1):"tag"==a?e(3,b):"load"==a?b&&b():"auth"==a?e(14,b):"identify"==a?D(Ja,f,b,c,d):"alias"==a?e(13,b):"unidentify"==a?D(function(){this.g(13)&&(this.s(13),J(this).oa(1))}):"props"==a||"properties"==a?e(4,b):"chat"==a&&R([b,c,d])}}var n,K,L=h._gs||(K=1,function(){va.push(arguments)}),va=L.q=L.q||[];if(!L.v){var r=h.GoSquared,P={},ma=0,H,V,W,Z=["data","data2"],Y=0|N.random()*
Z[F],Ba=/^https:/.test(location.href),ta,k={};if(r){C(r,function(a,b){"acct"==b?(ea(a,"_default",1),L(function(){function c(a){d[a.shift()].apply(d,a)}var d=r.DefaultTracker=k._default;if(b=r.q)for(;a=b.shift();)c(a);r.q={push:c};(b=r.load)&&b(d)})):"load"!=b&&"q"!=b&&L("set",b,a)});var w=ua.prototype;w.TrackView=da;w.TrackEvent=ca;w.Cancel=function(){this.N()};r.Tracker=ea;r.Cancel=m(v,0,"cancel")}h._gs=v;for(v.v=ga;w=va.shift();)v.apply({},w);if(K){K=l[ja]("script");for(var w=K[F],wa;w--;)(wa=K[w].getAttribute("data-gs"))&&
v(wa)}na();A(h,"load",na)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,"6.3.1800","createElement","split","replace","length","toLowerCase","name","getElementsByTagName","indexOf");
